api/urls.py
from django.urls import path
from api.views import AdminLogin, CustomerAPIView, CustomerCreateAPIView, HelloWorldView, MachineSlotsAPIView, SetMachineIdAndPassword, TransactionCreateAPIView, VendingMashineCallBackAPI, check_app_update
from backend import views
urlpatterns = [
    # path('api/', views.home, name="home"),
    path('hello/', HelloWorldView.as_view(), name='hello-world'),
    path('customer/<str:phone_number>/', CustomerAPIView.as_view(), name='customer-detail'),
    path('customer-create/', CustomerCreateAPIView.as_view(), name='customer-create'),
    path('transaction-create/', TransactionCreateAPIView.as_view(),
         name='transaction-create'),
    path('vending/', VendingMashineCallBackAPI.as_view(), name='vending-machine-callback'),
    path('machine-slots/<str:machine_id>', MachineSlotsAPIView.as_view(), name='machine-slots'),
    path('machine-slots/',
         MachineSlotsAPIView.as_view(), name='machine-slots'),

    path('machine-login/', SetMachineIdAndPassword.as_view(), name="machine-login"),
    path('admin-login/', AdminLogin.as_view(), name="admin-login"),
    path('check-app-update/', check_app_update, name='check-app-update'),

]

indepth/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('api/auth/', include('rest_framework.urls')),
    path('backend/', include('backend.urls')),
    
    
    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='auth/password_reset.html'), name='password_reset'),

    # After requesting a password reset
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='auth/password_reset_done.html'), name='password_reset_done'),

    # Password reset confirmation link page
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='auth/password_reset_confirm.html'), name='password_reset_confirm'),

    # Password reset complete page
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='auth/password_reset_complete.html'), name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

backend/models.py
import datetime
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Q

# Create your models here.

CUSTOMER_TYPES = (
    ('General Population', 'General Population'),
    ('Client Group', 'Client Group'),
)

CLIENT_GROUPS = (
    ('FSW', 'FSW'),
    ('MSM', 'MSM'),
    ('PWID,', 'PWID,'),
    ('MAT,', 'MAT,'),
    ('AGYW,', 'AGYW,'),
)
GENDERS = (
    ('Male', 'Male'),
    ('Female', 'Female'),
)

PRODUCT_TYPES = (
    ('Condoms', 'Condoms'),
    ('Kits', 'Kits'),
)
PRODUCT_SUBTYPES = (
    ('Male Condoms', 'Male Condoms'),
    ('Female Condoms', 'Female Condoms'),
    ('Blood Kits', 'Blood Kits'),
    ('Oral Kits', 'Oral Kits'),
)


PIN_TYPES = (
    ('PERMANENT', 'PERMANENT'),
)


TRANSCTION_STATUSES  = (
    ('Pending', 'Pending'),
    ('Processing', 'Processing'),
    ('Completed', 'Completed'),
    ('Failed', 'Failed'),
)
class Machine(models.Model):
    name = models.CharField(max_length=50)
    machine_id = models.CharField(max_length=50, unique=True)
    location = models.CharField(max_length=50, null=True, blank=True)
    status = models.CharField(max_length=50, null=True, blank=True)
    password = models.CharField(max_length=50, null=True, blank=True)
    description = models.TextField(max_length=200, null=True, blank=True)
    last_online = models.DateTimeField(null=True, blank=True)
    
    # def get_online_status(self):
    #     ##if last_online is 10 seconds ago then the machine is online
    #     if self.last_online and datetime.datetime.now() - self.last_online < datetime.timedelta(seconds=10):
    #         return "Online"
    #     else:
    #         return "Offline"
    def remained_condoms(self):
        slots = Slot.objects.filter(machine=self, product_type= "Condoms")
        return sum(slot.quantity_available for slot in slots)
    def remained_kits(self):
        slots = Slot.objects.filter(machine=self,  product_type="Kits")
        return sum(slot.quantity_available for slot in slots if slot.product_type == "Kits")
    def condom_capacity(self):
        return sum(slot.capacity for slot in Slot.objects.filter(machine=self, product_type="Condoms"))
    def kit_capacity(self):
        return sum(slot.capacity for slot in Slot.objects.filter(machine=self, product_type="Kits"))
        
        
    
    def __str__(self):
        return self.name + self.machine_id
    
class Slot(models.Model):
    name = models.CharField(max_length=50)
    slot_number  = models.IntegerField()
    machine = models.ForeignKey(Machine, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='slots/', null=True, blank=True)
    product_type = models.CharField(max_length=50, choices=PRODUCT_TYPES)
    product_subtype = models.CharField(max_length=50, choices=PRODUCT_SUBTYPES, blank=True, null=True)
    capacity = models.IntegerField()
    quantity_available = models.IntegerField()
    price = models.IntegerField(null=True, blank=True)
    product_image = models.ImageField(upload_to="product_images", null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def stock(self):
        return f"{self.quantity_available}/{self.capacity}"
    
    def get_product_id(self):
        if self.product_type == "Kits":
            return "222"
        else:
            return "111"
    
    
    def __str__(self):
        return self.name


class Customer(models.Model):
    name = models.CharField(max_length=50, null=True, blank=True)
    location = models.CharField(max_length=50, null=True, blank=True)
    type = models.TextField(max_length=200, choices=CUSTOMER_TYPES)
    client_group = models.TextField(max_length=200, null=True, blank=True, choices=CLIENT_GROUPS)
    phone_number = models.CharField(max_length=50, null=True, blank=True)
    age = models.CharField(max_length=50, null=True, blank=True)
    gender = models.CharField(max_length=50, null=True, blank=True, choices=GENDERS)
    registered_machine = models.ForeignKey(Machine, on_delete=models.CASCADE, null=True, blank=True)
    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    ##for KVP PINS
    pin = models.CharField(max_length=50, null=True, blank=True, unique=True)
    pin_type = models.CharField(
        max_length=50, null=True, blank=True, choices=PIN_TYPES)
    expire_date = models.DateField(null=True, blank=True)
    description = models.CharField(max_length=200, null=True, blank=True)
    status = models.CharField(max_length=50, null=True, blank=True)
    hotspot = models.CharField(max_length=50, null=True, blank=True)
    
    def __str__(self):
        return self.phone_number if self.phone_number else self.pin
    
    

    @property
    def condom_transaction_limit(self):
        return self.transaction_limit()["condom"]
    
    @property
    def kits_transaction_limit(self):
        return self.transaction_limit()["kits"]
    
    @property       
    def today_condom_transactions(self):
        today = datetime.date.today()
        transactions = Transaction.objects.filter(customer=self, product_type="Condoms", created_at__date=today)
        transaction_logs_count = TransactionLog.objects.filter(
            transaction__in=transactions).count()
        return transaction_logs_count

        return transactions.count()
    @property
    def today_kits_transactions(self):
        today = datetime.date.today()
        transactions = Transaction.objects.filter(customer=self,product_type="Kits",created_at__date=today)
        transaction_logs_count = TransactionLog.objects.filter(transaction__in=transactions).count()
        return transaction_logs_count
    
    def transactions(self):
        return Transaction.objects.filter(customer=self)
    def transaction_limit(self):
        type = self.type
        if type == "General Population":
            limits = { "condom": 3, "kits": 3}
            return  limits
        elif type == "Client Group":
            if self.client_group == "FSW":
                limits = { "condom": 5, "kits": 3}
                return  limits
            elif self.client_group == "MSM":
                limits = { "condom": 5, "kits": 3}
                return  limits
            elif self.client_group == "PWID":
                limits = { "condom": 5, "kits": 3}
                return  limits
            elif self.client_group == "MAT":
                limits = { "condom": 5, "kits": 3}
                return  limits
            elif self.client_group == "AGYW":
                limits = { "condom": 5, "kits": 3}

class Transaction(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    machine = models.ForeignKey(Machine, on_delete=models.CASCADE)
    amount = models.IntegerField(default=0)
    dispensed_amount = models.IntegerField(default=0)
    dispensed_successful_amount = models.IntegerField(default=0)
    slot = models.ForeignKey(Slot, on_delete=models.CASCADE, null=True, blank=True)
    product_type = models.CharField(
        max_length=50, null=True, blank=True, choices=PRODUCT_TYPES, )
    status = models.CharField(max_length=50, null=True,
                              blank=True, choices=TRANSCTION_STATUSES, default="Pending")
    kvp_pin = models.ForeignKey('Facility', null=True, blank=True, on_delete=models.SET_NULL)
    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    
    @property
    def dispensed_products_count(self):
        status = Q(feedback_status="0") | Q(feedback_status="2")
        return TransactionLog.objects.filter(transaction=self).filter(status).count()
    @property
    def get_status(self):
        if self.amount == self.dispensed_products_count:
            return "Succefully"
        elif self.amount > self.dispensed_products_count and self.dispensed_products_count !=0:
            return "Partially"
        else:
            return "Pending"
    
    def __str__(self):
        
        numbr = self.customer.phone_number if self.customer.phone_number else self.customer.pin
        return numbr  + self.product_type + str(self.amount)

class TransactionLog(models.Model):
    transaction = models.ForeignKey(Transaction, on_delete=models.CASCADE)
    machine = models.ForeignKey(Machine, on_delete=models.CASCADE)
    slot = models.ForeignKey(Slot, on_delete=models.CASCADE)
    product_type = models.CharField(
        max_length=50, null=True, blank=True, choices=PRODUCT_TYPES)
    status = models.CharField(max_length=50, null=True,  blank=True,
                              choices=TRANSCTION_STATUSES, default="Pending")
    status_description = models.CharField(max_length=200, null=True, blank=True)
    feedback_status = models.CharField(max_length=20, null=True, blank=True)
    trade_number = models.CharField(max_length=200, null=True, blank=True)
    index = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.transaction.customer.phone_number if self.transaction.customer.phone_number else self.transaction.customer.pin + self.product_type + "Log" + " " + "Status " + self.status

class Facility(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    machine = models.ForeignKey(Machine, null=True, blank=True, on_delete=models.CASCADE)
    district = models.CharField(
        max_length=100, verbose_name="District Supporting Ward",  null=True, blank=True)
    ward = models.CharField(
        max_length=100, verbose_name="Supporting Ward",  null=True, blank=True)
    hfrcode = models.CharField(
        max_length=15, verbose_name="HFR Code", null=True, blank=True)
    supporting_facility = models.CharField(
        max_length=100, verbose_name="Supporting Facility",  null=True, blank=True)

templates/snippets/base.html
{% load static %} {% include 'snippets/head.html' %}

  <body>
    {% include 'snippets/topbar.html' %}
    <!-- Top Bar End -->

    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/heatmap.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>

    <!-- leftbar-tab-menu -->
    {% include 'snippets/sidebar.html' %}
    <!--end startbar-->

    <div class="startbar-overlay d-print-none"></div>
    <!-- end leftbar-tab-menu-->

    
    {% block content %}
        
    {% endblock content %}
        

    {% include 'snippets/footer.html' %}
  </body>
  <!--end body-->
</html>

templates/snippets/cutomer_filters.html
{% load custom_filters %}

<div class="container">
  <form method="get" class="mb-4">
    <div class="row g-3 align-items-end">
      <!-- Phone Number Filter -->
      <div class="col-md-2">
        <label for="id_phone_number" class="form-label">
          {{ filter.form.phone_number.label }}
        </label>
        {{ filter.form.phone_number|add_class:"form-control" }}
      </div>
      <!-- Gender Filter -->
      <div class="col-md-2">
        <label for="id_gender" class="form-label">
          {{ filter.form.gender.label }}
        </label>
        {{ filter.form.gender|add_class:"form-select" }}
      </div>
      <!-- Customer Type Filter -->
      <div class="col-md-2">
        <label for="id_type" class="form-label">
          {{ filter.form.type.label }}
        </label>
        {{ filter.form.type|add_class:"form-select" }}
      </div>

      <!-- Age Range Filter -->
       <!-- Age Range Filter -->
      <div class="col-md-2">
        <label for="age_range" class="form-label">Age Range</label>
        {{ filter.form.age_range|add_class:"form-select" }}
      </div>

      <!-- Buttons -->
      <div class="col-md-4">
        <div class="d-flex">
          <button type="submit" class="btn btn-primary w-20 m-1">Filter</button>
          <a href="{% url 'customers' %}" class="btn btn-outline-primary w-20 m-1">Clear</a>
        </div>
      </div>
    </div>
  </form>
</div>

templates/snippets/footer.html
    {% load static %}
    
    <script src="{% static 'assets/libs/bootstrap/js/bootstrap.bundle.min.js'  %}"></script>
    <script src="{% static 'assets/libs/simplebar/simplebar.min.js'  %}"></script>

    <script src="{% static 'assets/libs/apexcharts/apexcharts.min.js'  %}"></script>
    <script src="{% static 'assets/data/stock-prices.js'  %}"></script>
    <script src="{% static 'assets/libs/jsvectormap/js/jsvectormap.min.js'  %}"></script>
    <script src="{% static 'assets/libs/jsvectormap/maps/world.js'  %}"></script>
    <script src="{% static 'assets/js/pages/index.init.js'  %}"></script>
    <script src="{% static 'assets/js/app.js'  %}"></script>



        {% comment %} <script src="{%  static 'assets/libs/simplebar/simplebar.min.js' %}"></script>
        <script src="{%  static 'assets/libs/simple-datatables/umd/simple-datatables.js' %}"></script>
        <script src="{%  static 'assets/js/pages/datatable.init.js' %}"></script> {% endcomment %}

templates/snippets/head.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr" data-startbar="light" data-bs-theme="light">
  <head>
    <meta charset="utf-8" />
    <title>HJFMRI - Vending Mashines MAnagement System</title>
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta
      content="HJFMRI - Vending Mashines MAnagement System"
      name="description"
    />
    <meta content="" name="author" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <link
      rel="shortcut icon"
      href="{% static 'assets/logos/favicon/favicon.ico'  %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'assets/libs/jsvectormap/css/jsvectormap.min.css'  %}"
    />
    <!-- App css -->
    <link
      href="{% static 'assets/css/bootstrap.min.css'  %}"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="{% static 'assets/css/icons.min.css'  %}"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="{% static 'assets/css/app.min.css'  %}"
      rel="stylesheet"
      type="text/css"
    />

    <link
      href="https://code.highcharts.com/dashboards/css/dashboards.css"
      rel="stylesheet"
      type="text/css"
    />
  </head>
</html>

templates/snippets/messages.html
{% if messages %}
<div class="alert alert-danger m-1 p-1 text-center">
  {% for message in messages %}
  <p>{{ message }}</p>
  {% endfor %}
</div>
{% endif %}

templates/snippets/sidebar.html
{% load static %}

<div class="startbar d-print-none">
  <style>
    .logg {
      margin-left: -70px;
    }
  </style>

  <div class="startbar d-print-none">
    <!--start brand-->
    <div class="brand">
      <a href="{% url 'index' %}" class="logo">
        <span>
          {% comment %}
          <img
            src="{% static 'assets/logos/logo22.png'  %}"
            alt="logo-small"
            class="logo-sm"
            height="40"
          />
          {% endcomment %}
        </span>
        <span class="logg">
          <img
            src="{% static 'assets/logos/logowhite.png'  %}"
        alt="logo-large"
            class="logo-lg logo-light"
            height="80"
          />
          <img
            src="{% static 'assets/logos/logo22.png'  %}"
            alt="logo-large"
            class="logo-lg logo-dark"
            height="80"
          />
        </span>
      </a>
    </div>

    <!--start brand-->
    {% comment %}
    <div class="brand">
      <a href="{% url 'index' %}" class="logo">
        <span>
          <img
            src="{% static 'assets/images/logo-sm.png'  %}"
            alt="logo-small"
            class="logo-sm"
          />
        </span>
        <span class="">
          <img
            src="{% static 'assets/images/logo-light.png'  %}"
            alt="logo-large"
            class="logo-lg logo-light"
          />
          <img
            src="{% static 'assets/images/logo-dark.png'  %}"
            alt="logo-large"
            class="logo-lg logo-dark"
          />
        </span>
      </a>
    </div>
    {% endcomment %}
    <!--end brand-->
    <!--start startbar-menu-->
    <div class="startbar-menu">
      <div class="startbar-collapse" id="startbarCollapse" data-simplebar>
        <div class="d-flex align-items-start flex-column w-100">
          <!-- Navigation -->
          <ul class="navbar-nav mb-auto w-100">
            <li class="menu-label pt-0 mt-0">
              <!-- <small class="label-border">
                                <div class="border_left hidden-xs"></div>
                                <div class="border_right"></div>
                            </small> -->
              <span>Main Menu</span>
            </li>
            <li class="nav-item">
              <a
              href="{% url 'index' %}"
                class="nav-link"
               
                role="button"
                aria-expanded="false"
              >
                <i class="iconoir-home-simple menu-icon"></i>
                <span>Dashboard</span>
              </a>
              <div class="collapse" id="sidebarDashboards">
                
                <!--end nav-->
              </div>
              <!--end startbarDashboards-->
            </li>
            <!--end nav-item-->
            <li class="nav-item">
              <a
                class="nav-link"
                href="#sidebarApplications"
                data-bs-toggle="collapse"
                role="button"
                aria-expanded="false"
                aria-controls="sidebarApplications"
              >
                <i class="iconoir-view-grid menu-icon"></i>
                <span>Mashines</span>
              </a>
              <div class="collapse" id="sidebarApplications">
                <ul class="nav flex-column">

                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'mashines' %}">All</a>
                  </li>
              
                  <!--end nav-item-->
                </ul>
                <!--end nav-->
              </div>
              <!--end startbarApplications-->
            </li>
            <!--end nav-item-->
            {% comment %} <li class="menu-label mt-2">
              <small class="label-border">
                <div class="border_left hidden-xs"></div>
                <div class="border_right"></div>
              </small>
              <span>Components</span>
            </li> {% endcomment %}
            <li class="nav-item">
              <a
                class="nav-link"
                href="#sidebarElements"
                data-bs-toggle="collapse"
                role="button"
                aria-expanded="false"
                aria-controls="sidebarElements"
              >
                <i class="iconoir-compact-disc menu-icon"></i>
                <span>Customers</span>
              </a>
              <div class="collapse" id="sidebarElements">
                <ul class="nav flex-column">
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'customers' %}">All</a>
                  </li>
                  <!--end nav-item-->
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'kvp_customers' %}?type=Client+Group">KVP Customers</a>
                  </li>
                    <li class="nav-item">
                    <a class="nav-link" href="{% url 'kvp_pins' %}">KVP Pins</a>
                  </li>
                  <!--end nav-item-->
                  
                  <!--end nav-item-->
                </ul>
                <!--end nav-->
              </div>
              <!--end startbarElements-->
            </li>
            <!--end nav-item-->
          
            <!--end nav-item-->
            <li class="nav-item">
              <a
                class="nav-link"
                href="#sidebarForms"
                data-bs-toggle="collapse"
                role="button"
                aria-expanded="false"
                aria-controls="sidebarForms"
              >
                <i class="iconoir-journal-page menu-icon"></i>
                <span>Staffs</span>
              </a>
              <div class="collapse" id="sidebarForms">
                <ul class="nav flex-column">
            
                  <!--end nav-item-->
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'staff' %}"
                      >All</a
                    >
                  </li>

                   <li class="nav-item">
                    <a class="nav-link" href="{% url 'facilities' %}"
                      >Facilities</a
                    >
                  </li>

                  <!--end nav-item-->
                </ul>
                <!--end nav-->
              </div>
              <!--end startbarForms-->
            </li>
            <!--end nav-item-->
            <li class="nav-item">
              <a
                class="nav-link"
                href="#sidebarCharts"
                data-bs-toggle="collapse"
                role="button"
                aria-expanded="false"
                aria-controls="sidebarCharts"
              >
                <i class="iconoir-candlestick-chart menu-icon"></i>
                <span>Reports</span>
              </a>
              <div class="collapse" id="sidebarCharts">
                <ul class="nav flex-column">
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'transactions' %}">Transactions</a>
                  </li>
                     <li class="nav-item">
                    <a class="nav-link" href="{% url 'transactions_logs'  %}">Transaction Logs</a>
                  </li>
                </ul>
                <!--end nav-->
              </div>
              <!--end startbarCharts-->
            </li>
            <!--end nav-item-->
            <li class="nav-item">
              <a
                class="nav-link"
                href="#sidebarTables"
                data-bs-toggle="collapse"
                role="button"
                aria-expanded="false"
                aria-controls="sidebarTables"
              >
                <i class="iconoir-table-rows menu-icon"></i>
                <span>Products</span>
              </a>
              <div class="collapse" id="sidebarTables">
                <ul class="nav flex-column">
                  <li class="nav-item">
                    <a class="nav-link" href="/products">All</a>
                  </li>
                  
                </ul>
                <!--end nav-->
              </div>
              <!--end startbarTables-->
            </li>
            <!--end nav-item-->
           
        
            <!--end nav-item-->
            
            <!--end nav-item-->
            <li class="menu-label mt-2">
              <small class="label-border">
                <div class="border_left hidden-xs"></div>
                <div class="border_right"></div>
              </small>
              <span>Crafted</span>
            </li>
            <li class="nav-item">
              <a
                class="nav-link"
                href="#sidebarPages"
                data-bs-toggle="collapse"
                role="button"
                aria-expanded="false"
                aria-controls="sidebarPages"
              >
                <i class="iconoir-page-star menu-icon"></i>
                <span>More</span>
              </a>
              <div class="collapse" id="sidebarPages">
                <ul class="nav flex-column">
                  <li class="nav-item">
                    <a class="nav-link" href="/sms">SMS Configurations</a>
                  </li>
                  <!--end nav-item-->
                  <li class="nav-item">
                    <a class="nav-link" href="/sms"
                      >Email Configurations</a
                    >
                  </li>
                  <!--end nav-item-->
                 
                
                  <!--end nav-item-->
                  <li class="nav-item">
                    <a class="nav-link" href="/api">API</a>
                  </li>
                  <!--end nav-item-->
                </ul>
                <!--end nav-->
              </div>
              <!--end startbarPages-->
            </li>


            
            <!--end nav-item-->
            <li class="nav-item">
              <a
                class="nav-link"
                href="#sidebarAuthentication"
                data-bs-toggle="collapse"
                role="button"
                aria-expanded="false"
                aria-controls="sidebarAuthentication"
              >
                <i class="iconoir-fingerprint-lock-circle menu-icon"></i>
                <span>Settings</span>
              </a>
              <div class="collapse" id="sidebarAuthentication">
                <ul class="nav flex-column">
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'permissions' %}">Permissions</a>
                  </li>
                  <!--end nav-item-->
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'roles' %}">Roles</a>
                  </li>
                  <!--end nav-item-->
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'audit_logs' %}"
                      >Audit Logs</a
                    >
                  </li>
                  <!--end nav-item-->
                  <li class="nav-item">
                    <a class="nav-link" href="/backups"
                      >Backups</a
                    >
                  </li>
                  <!--end nav-item-->
                 
                  <!--end nav-item-->
                </ul>
                <!--end nav-->
              </div>
              <!--end startbarAuthentication-->
            </li>
            <!--end nav-item-->
          </ul>
         
        </div>
      </div>
      <!--end startbar-collapse-->
    </div>
    <!--end startbar-menu-->
  </div>
</div>